apiVersion: v1
kind: Pod
metadata:
    name: test-pod
    labels:
        tier: frontend
spec:
    containers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80
    restartPolicy: OnFailure