apiVersion: v1
kind: Pod
metadata:
    name: static-pod
    labels:
        tier: static-pod
spec:
    containers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80
    restartPolicy: OnFailure